### ISSUE TITLE
Receiver never emits packet event from outside data

### ISSUE THREAD

**Issue by bootsie123** [stagehacks/stagehack-sACN#1]
Hi! I'm currently running into issues when trying to use the receiver. Sending data through the sender works fine. And I'm able to receive the sent data with the receiver. However, when data is sent from another source on the sACN network, the `packet` event never seems to be emitted. I don't get any error messages either. Any ideas? I'm currently using this in a setup with OLA

My code is as follows:

```const ACNSender = require("stagehack-sacn").Sender;
const ACNReceiver = require("stagehack-sacn").Receiver;

ACNSender.Start();
ACNReceiver.Start();

const sender = new ACNSender.Universe(1);

sender.on("ready", () => {
  console.log("Sender Ready");

  sender.send([255]);
});


const receiver = new ACNReceiver.Universe(1);

receiver.on("ready", () => {
  console.log("Receiver Ready");

  receiver.on("packet", function(packet) {
    console.log("Packet Received", packet.getSource());
  });
});```

**Comment by sparks-alec** [comment]
Hmmm, can you elaborate more on your network setup? I am running your code on my Mac and am seeing successful "Packet Received" logs. Tried both ETC Eos and QLC+ sources too!

Do the sACN packets show up in sACNView on the same computer?

Also, make sure you're on the latest version! I just put out 1.0.7 a few days ago.

**Comment by bootsie123** [comment]
Hi! Thanks for getting back to me! I haven't given ETC EOS or QLC+ a try yet, but considering everything is running on your end, my guess is it's probably something to do with my network setup. Let me give those a try along with sACNView and I'll get back to you on that
